const fs = require('fs');
const lines = [
'"use client";',
'',
'import { useState } from "react";',
'import { useRouter } from "next/navigation";',
'import Link from "next/link";',
'import { api } from "@/lib/api";',
'',
'export default function LoginPage() {',
'  const router = useRouter();',
'  const [email, setEmail] = useState("");',
'  const [password, setPassword] = useState("");',
'  const [loading, setLoading] = useState(false);',
'  const [error, setError] = useState(null);',
'',
'  const handleLogin = async (e) => {',
'    e.preventDefault();',
'    setError(null);',
'    setLoading(true);',
'    try {',
'      const res = await api.post("/auth/login", { email, password });',
'      const { token, user } = res.data;',
'      localStorage.setItem("token", token);',
'      localStorage.setItem("role", user.role);',
'      localStorage.setItem("user_id", String(user.user_id));',
'      localStorage.setItem("email", user.email);',
'      if (user.role === "doctor") {',
'        router.push("/doctor");',
'      } else if (user.role === "admin") {',
'        router.push("/admin");',
'      } else {',
'        router.push("/");',
'      }',
'    } catch (err) {',
'      setError(err?.response?.data?.message || "Login failed.");',
'    } finally {',
'      setLoading(false);',
'    }',
'  };',
'',
'  return (',
'    <main className="flex min-h-screen items-center justify-center bg-slate-950 px-4">',
'      <div className="w-full max-w-sm rounded-2xl border border-slate-800 bg-slate-900/80 p-6 shadow-xl">',
'        <h1 className="mb-1 text-xl font-semibold text-slate-50">Sign in to MediHive</h1>',
'        <p className="mb-6 text-xs text-slate-400">Patients, doctors, and admins use the same login.</p>',
'        {error && (',
'          <div className="mb-4 rounded-lg bg-red-500/10 px-4 py-3 text-sm text-red-400">{error}</div>',
'        )}',
'        <form onSubmit={handleLogin} className="space-y-4">',
'          <div>',
'            abel className="mb-1 block text-xs text-slate-400">Email</label>',
'            <input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" className="w-full rounded-lg border border-slate-700 bg-slate-800 px-4 py-2 text-sm text-slate-50 outline-none placeholder:text-slate-500 focus:border-teal-500" />',
'          </div>',
'          <div>',
'            abel className="mb-1 block text-xs text-slate-400">Password</label>',
'            <input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="••••••••" className="w-full rounded-lg border border-slate-700 bg-slate-800 px-4 py-2 text-sm text-slate-50 outline-none placeholder:text-slate-500 focus:border-teal-500" />',
'          </div>',
'          <button type="submit" disabled={loading} className="w-full rounded-full bg-teal-500 py-2 text-sm font-medium text-slate-950 hover:bg-teal-400 disabled:o           {loading ? "Signing in..." : "Sign in"}',
'          </button>',
'        </form>',
'        <p className="mt-4 text-center text-xs text-slate-400">',
'          Do not have an account?{" "}',
'          <Link href="/auth/register" className="text-teal-400 underline">Register</Link>',
'        </p>',
'      </div>',
'    </main>',
'  );',
'}',
];
fs.writeFileSync('src/app/auth/login/page.tsx', lines.join('\n'));
console.log('Done');

